source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'UPnPDA_Example' do
  pod 'UPnPDA', :path => '../'

  target 'UPnPDA_Tests' do
    inherit! :search_paths

    
  end
end
